site_name: æternity Documentation Hub
nav:
    - Introduction: 'index.md'
    - Quick Glossary: 'quick_glossary.md'
    - Node:
        - Introduction: 'æternity/README.md'
        - Get Started:
            - Build in Windows: 'æternity/docs/build-windows.md'
            - Build in Ubuntu: 'æternity/docs/build.md'
            - Configuration: 'æternity/docs/configuration.md'
            - CUDA Miner: 'æternity/docs/cuda-miner.md'
            - Docker: 'æternity/docs/docker.md'
            - Installation in Windows: 'æternity/docs/installation-windows.md'
            - Installation in Ubuntu: 'æternity/docs/installation.md'
            - Operation: 'æternity/docs/operation.md'
    - Protocol:
        - Oracles:
            - Life Cycle: 'protocol/oracles/oracle_life_cycle.md'
            - State Tree: 'protocol/oracles/oracle_state_tree.md'
            - Transactions: 'protocol/oracles/oracle_transactions.md'
        - AENS Naming System: 'protocol/AENS.md'
        - Smart Contracts:
            - Contract Life Cycle Examples: 'protocol/contracts/contract_life_cycle.md'
            - Virtual Machines:
                - Æternity VM: 'protocol/contracts/contract_vms.md'
                - Æternity Ethereum VM: 'protocol/contracts/aevm.md'
            - Sophia Smart Contract Language: 'protocol/contracts/sophia.md'
            - Contract State Tree: 'protocol/contracts/contract_state_tree.md'
            - Contract Transactions: 'protocol/contracts/contract_transactions.md'
        - State Channels: 'protocol/channels/README.md'
        - Serialization Formats: 'protocol/serializations.md'
    - Expansions:
        - AEX1: 'Expansions/AEXS/aex-1.md'
        - AEX2: 'Expansions/AEXS/aex-2.md'
    - Node Usage API:
        - Latest Stable Release:
            - Autogenerated æternity Node API Documentation: 'api-docs/README.me'
        - Encoding Scheme: 'protocol/node/api/api_encoding.md'
        - Account Managment: 'protocol/node/api/account_api_usage.md'
        - Spending Tokens: 'protocol/node/api/spend_api_usage.md'
        - Oracle: 'protocol/node/api/oracle_api_usage.md'
        - Naming System: 'protocol/node/api/naming_system_api_usage.md'
        - Contract: 'protocol/node/api/contract_api_usage.md'
        - Channels: 'protocol/node/api/channels_api_usage.md'
        - Mining: 'protocol/node/api/mining_api_usage.md'
    - Developer Tools:
        - SDKs:
            - Go: 'developer-tools/sdks/sdk-go/README.md'
            - JavaScript: 'developer-tools/sdks/sdk-js/README.md'
            - Python: 'developer-tools/sdks/sdk-python/README.md'
        - Middleware: 'developer-tools/aepp-middleware/README.md'
        - Token Faucet: 'developer-tools/aepp-faucet/README.md'
        - Frameworks:
            - ForgAE: 'developer-tools/frameworks/forgae/README.md'
            - Components: 'developer-tools/frameworks/aepp-components/README.md'
        - Contract Editor: 'developer-tools/aepp-contracts/README.md'
    #     - CLI Tools:
    #         - JavaScript
    #         - Stratum:
    #            - Library
    #         - Websocket
    #     - Middleware:
    #     - Frameworks:
    #         - ForgAE
    #         - æpp Components
    #     - Online Test Tools:
    #         - Smart Contract Editor
    #         - Blockchain Explorer
    #         - Faucet
    #            - Token Faucet
    #            - æpp Faucet
    - Sophia Libraries:
        - DateTime: 'aepp-sophia-examples/libraries/DateTime/README.md'
        - List: 'aepp-sophia-examples/libraries/List/README.md'
        - Ownable: 'aepp-sophia-examples/libraries/Ownable/README.md'
        - FungibleToken: 'aepp-sophia-examples/libraries/FungibleToken/README.md'
        - NonFungibleToken: 'aepp-sophia-examples/libraries/NonFungibleToken/README.md'
        - MultisignatureWallet: 'aepp-sophia-examples/libraries/MultisignatureWallet/README.md'
    - Sophia by Example:
        #- CryptoHamster: 'aepp-sophia-examples/examples/CryptoHamster/README.md'
        - Smart Data Provider: 'aepp-sophia-examples/examples/SmartDataProvider/README.md'
        - Smart Real Estate: 'aepp-sophia-examples/examples/SmartRealEstate/README.md'
        - Spend-to-Many: 'aepp-sophia-examples/examples/SpendToMany/README.md'
        - Tic Tac Toe: 'aepp-sophia-examples/examples/TicTacToe/README.md'
    - How-To Guides:
        - Account:
            - Create (in æ CLI): 'tutorials/account-creation-in-ae-cli.md'
        - Middleware:
            - Run Own Middleware: 'tutorials/running-your-own-ae-middleware.md'
        - Miner:
            - Run CPU Miner (Ubuntu): 'tutorials/run-cpu-miner-on-ubuntu-1804.md'
            - Run GPU Miner (Ubuntu): 'tutorials/run-gpu-miner-on-ubuntu-1804.md'
        - Node:
            - Run Node (MacOS): 'tutorials/run-node-on-macos-mojave.md'
            - Run Node (Ubuntu): 'tutorials/run-node-on-ubuntu-1804.md'
        - Paper Wallet:
            - Create (in æ CLI): 'tutorials/create-a-paper-wallet.md'
        - Sophia:
            - Install Sophia Notepad++ Language Definition: 'tutorials/sophia-language-definition-for-notepad++.md'
        - Testnet:
            - Run Local Testnet (Docker): 'tutorials/run-local-testnet-with-docker.md'
            - Get Testnet Tokens: 'tutorials/get-testnet-tokens.md'
        - Unit Tests:
            - How to Write Unit Test I: 'tutorials/how-to-write-unit-test-1.md'
            - How to Write Unit Test II: 'tutorials/how-to-write-unit-test-2.md'
    - Tutorials:
        - Oracles:
            - Sophia Oracle Introduction: 'tutorials/sophia-oracle-introduction.md'
        - Sophia:
            - Fungible Token Contract: 'tutorials/sophia-fungible-token-contract.md'
            - Token Exchange Contract I: 'tutorials/sophia-token-exchange-contract-1.md'
            - Token Exchange Contract II: 'tutorials/sophia-token-exchange-contract-2.md'
            - Token Exchange Contract III: 'tutorials/sophia-token-exchange-contract-3.md'
            - Vote Contract: 'tutorials/vote-contract.md'
        - State Channels:
            - Introduction: 'tutorials/state-channels-introduction.md'
extra_css: [site/assets/extra.css]
theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'white'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

repo_name: 'aeternity/documentation-hub'
repo_url: 'https://github.com/aeternity/documentation-hub'
